blank_issues_enabled: false
contact_links:
  - name: 💬 Genel Soru & Tartışma
    url: https://github.com/RaijuMounun/erenkeskinogludotcom/discussions
    about: Genel sorular, öneriler ve tartışmalar için Discussions bölümünü kullan
  - name: 📧 Doğrudan İletişim
    url: https://erenkeskinoglu.com/contact
    about: Kişisel konular için web sitesindeki iletişim formunu kullanabilirsin
  - name: 🐛 Güvenlik Açığı Bildirimi
    url: mailto:security@erenkeskinoglu.com
    about: Güvenlik açıkları için lütfen doğrudan e-posta gönder 