name: Yeni Özellik Talebi
description: Uygulamaya eklenmesini istediğiniz bir özelliği önerin
title: "[FEATURE] "
labels: [feature]
body:
  - type: textarea
    id: ozellik
    attributes:
      label: Özellik Açıklaması
      description: Bu özellik ne işe yarar?
    validations:
      required: true

  - type: textarea
    id: neden
    attributes:
      label: Neden Eklenmeli?
      description: Hangi problemi çözüyor? Kullanıcıya ne kazandırıyor?
