name: Planlama Görevi
description: Planlama ve analiz fazına ait işler için kullanılır.
title: "[PLANLAMA] "
labels: [planlama]
body:
  - type: input
    id: hedef
    attributes:
      label: Hedef Tanımı
      description: Bu görev neyi planlamak veya analiz etmek için yapılıyor?
    validations:
      required: true

  - type: textarea
    id: detaylar
    attributes:
      label: Detaylı Açıklama
      description: Planlanacak süreç, yapılacak analizler ve araştırılacak konular
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Yapılacaklar
      options:
        - label: Gereksinimler belirlendi
        - label: Analiz yapıldı
